# Jekyll
permalink: /post/:title.html
paginate: 15
exclude: [ theme.html, newpost.sh, node_modules, tumblr-oauth.yml, README* ]

# site-wide data
name: dropshado.ws
description: Front-end development minuti&aelig;
tagline: "A catalog of resources and tips I learn, discover and use in my career as a front-end developer. You should start one yourself."